source 'https://cdn.cocoapods.org/'

platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

target 'ScrollingStackViewController_Example' do
  pod 'ScrollingStackViewController', :path => '../'

  target 'ScrollingStackViewController_Tests' do
    inherit! :search_paths

    
  end
end
